language: objective-c
osx_image: xcode9.2
xcode_workspace: schulcloud.xcworkspace
xcode_scheme: iOS
xcode_sdk: iphonesimulator

env:
  matrix:
    - LINT=1
    - BUILD=1
  global:
    - secure: 0dhIbVOiMCEaaqjYM+qKdESOVL8fvDvcmh9/gb1zihBtKYFiSx+B0gTRD7vM1T+AttSfITfqpJ05LDHB+rLaQQgGK+QBWuborK3mxSe7ObD1fxI84sD92M8i2wkdK3INLcMeyBVis+M/GwMmEs69tRowxjVi/2iKeXwEkd9u9x3Qesgl56zI+Q7kI0BXZuYtcBqLIsI1oQiiv025ZkrYS5n5ccjd17ZEjaZZnep2hScZvhHnQeu00JyvC1XDwDDX6HnrJRtLO3hnQWsFe+sztckGOpI77czZU4r4INLcWfebkBr+9Eg/Kt4ATk+yjzMWADmSquEFHn3S9JW5jtOB7CwLQAUfgR/e7BKiRVy3BhqMdYm8sKNQDfyFbXwgN2gWAA+RDkyL2x0seHe18FTbBZfGRhBv27a4H/Bx83y9eOOMj4n5CFC0F/QhiRIJDA7W2krjWoYIck5DK6qgS48pUZsyJQYgLP9mIlHh1GFfU8KuWxIcm8quTCmcr6F+3IjKhUTVRwWc1AzepuO1Zm41joW1+X42XZw31cttn5tfuXyE5cvI1KrEFMFFU6co/vd5wgNTXhFf/RVS93X0zCP/LhqBTsjEuVVuzshpLyAFxqgBLWJN8bGpey7tYuW1yIoVVSRu7kEyuX1+ZJ4LpQycpYrIqOnNYJD+B4E8gtMod7E=
    - secure: kDJI4cmMSf3vgmn8kTpJ6jmnhvDlG5/YZdpUXnX4C2mzh4YYljWd4akW7NjFfRQEO2m/mD2utkk+0RMylgo6khqlr4v7JRScTIpKm+jDj648uGPZU4D7qz42Hc9T8+v+yp/AnBnRuV984lhCcmntQJrOySN4nArgEF1iQJOMyG0YWEMOdgXLxQhxT3Vg5gI3Lm88wMrqjKd2fi0uXlYDIE2K3eW7zEfNrhRW74CwohdhDIW+azo7norgMVYfxlxCx4vrm0O8P0WO/80yTK9Lkc4oQnUA6Y9SCTwktzmtIglJR0jHKI2FoKxEzPgJ4LNcDJBh19mfL6xvSi7D3U23H420dLV/G29+KuS8/+L8/ZjdAuQT/Jm0T1lAepZLNeIn6p0L2OAGWllnBkzt/znsxOnTC1CjqY4f2XJu5gPiAzyCmyuYw73cOhvRDKcKoauutxooyPZCt4tgtgVc0VaG0HLYrKkuIm1qOPtOBPx8ZrIteoR5J7M/2cjmRvD7HQuLrSjH7J/LktJLmqsyJDIsSV2Bw21tw1aiETN+Ao643rkreUkT4MU+SOMoEuypO6tjg04BRafFEhdbPNEexO6w33TTaLzZ+/xA4pUPRCZ/V1hS6/1E9kL2xCytMLMqoOfcm/RKZGjBS7c0dBm3c3CH9X2QBHnq2VpnFBZPHLAJqMw=

install:
  - bundle install --without documentation
  - bundle exec pod repo update > /dev/null
  - bundle exec pod install

before_script:
  - cp iOSUITests/Credentials.plist.dummy iOSUITests/Credentials.plist
  - defaults write schulcloudUITests/Credentials UI_TEST_USERNAME $UI_TEST_USERNAME
  - defaults write schulcloudUITests/Credentials UI_TEST_PASSWORD $UI_TEST_PASSWORD

script:
  - set -o pipefail
  - if [ "$BUILD" == 1 ]; then xcodebuild -workspace $TRAVIS_XCODE_WORKSPACE -scheme $TRAVIS_XCODE_SCHEME -sdk $TRAVIS_XCODE_SDK build | xcpretty; fi
  - if [ "$LINT" == 1 ]; then bundle exec danger --verbose; fi
