language: objective-c
osx_image: xcode9.4
xcode_workspace: schulcloud.xcworkspace
xcode_scheme: schulcloud
xcode_sdk: iphonesimulator

env:
  matrix:
    - LINT=1
    - BUILD=1

install:
  - bundle install --without documentation
  - bundle exec pod repo update > /dev/null
  - bundle exec pod install

script:
  - set -o pipefail
  - if [ "$BUILD" == 1 ]; then xcodebuild -workspace $TRAVIS_XCODE_WORKSPACE -scheme $TRAVIS_XCODE_SCHEME -sdk $TRAVIS_XCODE_SDK build | xcpretty; fi
  - if [ "$LINT" == 1 ]; then bundle exec danger --verbose; fi
