language: objective-c
osx_image: xcode9.2
xcode_workspace: schulcloud.xcworkspace
xcode_scheme: schulcloud
xcode_sdk: iphonesimulator

install:
  - bundle install --without documentation
  - bundle exec pod repo update > /dev/null
  - bundle exec pod install

script:
  - set -o pipefail
  - xcodebuild -workspace $TRAVIS_XCODE_WORKSPACE -scheme $TRAVIS_XCODE_SCHEME -sdk $TRAVIS_XCODE_SDK -configuration Debug build | xcpretty
