language: objective-c
osx_image: xcode9
xcode_workspace: schulcloud.xcworkspace
xcode_scheme: schulcloud
xcode_sdk: iphonesimulator

install:
  - bundle install --without documentation
  - bundle exec pod repo update > /dev/null
  - bundle exec pod install

before_script:
  - mv schulcloud/GoogleService-Info.plist schulcloud/GoogleService-Info.plist.bak
  - mv schulcloud/GoogleService-Info-dummy.plist schulcloud/GoogleService-Info.plist

script:
  - set -o pipefail
  - xcodebuild -workspace $TRAVIS_XCODE_WORKSPACE -scheme $TRAVIS_XCODE_SCHEME -sdk $TRAVIS_XCODE_SDK -configuration Debug build | xcpretty
