language: objective-c
osx_image: xcode9.4
xcode_workspace: schulcloud.xcworkspace
xcode_scheme: schulcloud
xcode_sdk: iphonesimulator

env:
  matrix:
    - LINT=1
    - TEST=1 SCHEME="Common"
    - TEST=1 SCHEME="schulcloud"

install:
  - bundle install --without documentation
  - bundle exec pod repo update > /dev/null
  - bundle exec pod install

script:
  - set -o pipefail
  - if [ "$TEST" == 1 ]; then bundle exec fastlane run scan scheme:$SCHEME; fi
  - if [ "$LINT" == 1 ]; then bundle exec danger --verbose; fi
